name: CI/CD for Backend

on:
  push:
    branches:
      - main
    paths:
      - myMeloMate/**  # Trigger only when files in the backend are changed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run tests
      run: mvn test
      working-directory: ./myMeloMate
      env:
        SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
        SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

    # - name: Build Backend with Maven
    #   run: |
    #     cd ./myMeloMate  # Navigate to the backend folder
    #     mvn clean package

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./myMeloMate

    - name: Deploy to Raspberry Pi
      env:
        PI_HOST: ${{ secrets.PI_HOST }}
        PI_USER: ${{ secrets.PI_USER }}
        PI_SSH_KEY: ${{ secrets.PI_SSH_KEY }}
      run: |
        echo "$PI_SSH_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no $PI_USER@$PI_HOST 'mkdir -p ~/mymelomate-backend'
        scp -i private_key.pem -o StrictHostKeyChecking=no myMeloMate/target/*.jar $PI_USER@$PI_HOST:~/mymelomate-backend/
        ssh -i private_key.pem -o StrictHostKeyChecking=no $PI_USER@$PI_HOST << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/mymelomate-backend/*.jar > ~/mymelomate-backend/mymelomate.log 2>&1 &
        EOF
    - name: Cleanup
      run: rm -f private_key.pem
